config/routes.rb
Rails.application.routes.draw do
  get "profile", to: "users#show"

  get 'users/show'
  devise_for :users
  root to: "pages#home"

  get "pages/profile", to: "pages#profile"

  # resources :bookings, except: %i[create]
  resources :hats, only: %i[new create edit update index show] do
    resources :bookings, only: %i[index create]
  end
  resources :bookings, only: %i[index] do
    resources :reviews, only: %i[new create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hat
  has_one :review, dependent: :destroy
  validates :start_date, :end_date, presence: true, uniqueness: { scope: :hat_id, message: "This hat is already booked for those dates." }
  validate :start_date_before_end_date
  validate :start_date_in_future

  private

  def start_date_before_end_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:start_date, "must be before end date")
    end
  end

  def start_date_in_future
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "must be in the future")
    end
  end
end

app/models/hat.rb
class Hat < ApplicationRecord
  self.inheritance_column = :not_type
  has_one_attached :photo
  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings

  include PgSearch::Model
  pg_search_scope :hat_search,
    against: %i[ name type location color description ],
    using: {
      tsearch: { prefix: true }
    }

  pg_search_scope :hat_type_search,
    against: %i[ type ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :booking_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :hats, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name date_of_birth bio photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name bio photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_hat, only: %i[create]

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.hat = @hat
    if @booking.save
      redirect_to hat_path(@booking.hat), notice: "Booking request was successfully made."
    else
      redirect_to hat_path(@booking.hat), alert: "Booking could not be created."
    end
  end

  def index
    @bookings = Booking.where(user: current_user)
    @review = Review.new
  end

  private

  def set_hat
    @hat = Hat.find(params[:hat_id])
  end

  def booking_params
    params.require(:booking).permit(:name, :start_date, :end_date)
  end
end

app/controllers/hats_controller.rb
class HatsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    if params[:type].present?
      @hats = Hat.hat_type_search(params[:type])
    elsif params[:query].present?
      @hats = Hat.hat_search(params[:query])
    else
      @hats = Hat.all
    end
  end

  def show
    @hat = Hat.find(params[:id])
    @booking = Booking.new
    @reviews = @hat.bookings.map(&:review).compact
  end

  def new
    @hat = Hat.new
  end

  def create
    @hat = Hat.new(hat_params)
    if @hat.save
      redirect_to @hat, notice: "Hat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @hat = Hat.find(params[:id])
  end

  def update
    @hat = Hat.find(params[:id])
    if @hat.update(hat_params)
      redirect_to @hat, notice: "hat was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def hat_params
    params.require(:hat).permit(:name, :size, :photo, :location, :type, :color, :description, :day_rate)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @hats = Hat.all
  end

  def profile
    @hats = Hat.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to hat_path(@booking.hat), notice: "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :booking_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @hats = @user.hats
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@hat, @booking], data: { controller: 'flatpickr' } do |f| %>
  <%= f.input :start_date, as: :date, label: "Hat-in" %>
  <%= f.input :end_date, as: :date, label: "Hatout" %>
  <%= f.submit "Reserve hat", class: "btn btn-primary row-form-btn mb-3" %>
<% end %>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Hat</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Price</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.hat.type, hat_path(booking.hat) %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <% num_days = (booking.end_date.to_date - booking.start_date.to_date).to_i %>
        <td><%= number_to_currency(booking.hat.day_rate * num_days, unit: "£") %></td>
        <td>
          <% if booking.end_date < Time.now && booking.review.nil? && booking.status == true %>
            <%= link_to "Review hat", new_booking_review_path(booking_id: booking.id) %>
          <% elsif booking.end_date < Time.now && booking.review %>
            <%= link_to "Review submitted", hat_path(booking.hat) %>
          <% elsif booking.status == false %>
            <%= "Booking declined" %>
          <% elsif booking.status == true %>
            <%= "Booking accepted" %>
          <% else %>
            <%= "Booking pending" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hats/_form.html.erb
<%= simple_form_for(@hat) do |f| %>
  <%= f.input :name %>
  <%= f.input :size %>
  <%= f.input :location %>
  <%= f.input :type %>
  <%= f.input :color %>
  <%= f.input :description %>
  <%= f.input :day_rate %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/hats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit Hat</h1>
        <div class="mt-3">
          <%= render "form", hat: @hat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hats/index.html.erb
<div class="container mt-3">
    <div class="row">
      <div class="col-6 my-2 mx-auto">
        <%= form_with url: hats_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "True hat love starts here" %>
        <%= submit_tag "Search", class: "btn btn-primary ms-2" %>
      <% end %>
    </div>
  </div>
</div>

<div class="card-container d-flex justify content between">
      <% @hats.each do |hat| %>
        <% reviews = hat.bookings.map(&:review).compact %>
        <% ratings = reviews.pluck(:rating) %>
        <% total_ratings = ratings.sum %>
        <% review_count = reviews.count %>
        <% average_rating = total_ratings.to_f / review_count %>
          <div class="card-product">
            <%= link_to hat_path(hat) do %>
            <img src= <%= cl_image_path hat.photo.key %> />
            <div class="product-info">
              <div class="d-flex justify-content-between">
                <p class="product-name"><%= hat.name %></p>
                <p class="product-price"><%= number_to_currency(hat.day_rate, unit: "£") %></p>
              </div>
            <div class="d-flex justify-content-between">
              <p class="product-location"><%= hat.location%></p>
              <p class="product-rating"><%= average_rating %><i class="fa-solid fa-star"></i></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/hats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new hat</h1>
        <div class="mt-3">
          <%= render "form", hat: @hat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hats/show.html.erb
<% ratings = @reviews.pluck(:rating) %>
      <% total_ratings = ratings.sum %>
      <% review_count = @reviews.count %>
      <% average_rating = total_ratings.to_f / review_count %>

<div class="container mt-3">
  <div class="row justify-content-evenly">
    <div class="p-2 col-sm-7">
      <h2><%= @hat.name %></h2>
    </div>
    <div class="p-2 col-sm-3">
    </div>
  </div>
  <div class="row justify-content-evenly">
    <div class="p-2 col-sm-7">
      <div class="hat-show-image mb-3" style="background-image: url('<%= cl_image_path @hat.photo.key, crop: :fill %>')"></div>
          <div class="border-bottom border-secondary-subtle mb-3">
            <p><%= @hat.description %></p>
          </div>
          <div class="border-bottom border-secondary-subtle mb-3">
            <p class="text-muted"><%= @hat.type %> · <%= @hat.size %>cm · <%= @hat.color %></p>
          </div>
          <div class="border-bottom border-secondary-subtle mb-3">
            <p class="lead"><i class="fa-sharp fa-solid fa-location-dot me-1"></i> <%= @hat.location %></p>
          </div>
          <div>
            <h4><i class="fa-solid fa-star"></i> <%= average_rating %> · (<%= pluralize review_count, "review" %>)</h4>
            <% @reviews.each do |review| %>
              <div>
                <% rating = review.rating %>
                <% (1..rating).each do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% (rating...5).each do %>
                  <i class="far fa-star"></i>
                <% end %>
                <p><%= review.content %></p>
              </div>
            <% end %>
          </div>
      </div>
    <div class="p-2 col-sm-3">
      <div class="sticky-booking-form bg-light shadow p-3 mb-5 bg-body-tertiary rounded border border-secondary-subtle">
        <div class="flex">
          <div class="flex align">
            <p><%= number_to_currency(@hat.day_rate, unit: "£") %> / day</p>
          </div>
          <div class="flex align">
            <p><i class="fa-solid fa-star"></i> <%= average_rating %> · (<%= pluralize review_count, "review" %>)</p>
          </div>
        </div>
        <%= render 'bookings/form' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ONLYHats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body id="bootstrap-override">
    <%= render 'shared/navbar'%>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>OnlyHats brings you headgear for all occasions</h1>
    <%= link_to "Browse the collection", hats_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="shpiel">
<p style="text-align:center">Got a fancy dress party coming up? Looking for a hat for a day at the races?</p>
<p style="text-align:center">We've got you covered at OnlyHats!</p>
</div>

<div class="d-flex justify-content-between card-container">
    <% @hats.each do |hat| %>
      <% reviews = hat.bookings.map(&:review).compact %>
      <% ratings = reviews.pluck(:rating) %>
      <% total_ratings = ratings.sum %>
      <% review_count = reviews.count %>
      <% average_rating = total_ratings.to_f / review_count %>
        <div class="card-product">
          <%= link_to hat_path(hat) do %>
          <img src= <%= cl_image_path hat.photo.key %> />
          <div class="product-info">
            <div class="d-flex justify-content-between">
              <p class="product-name"><%= hat.name %></p>
              <p class="product-price"><%= number_to_currency(hat.day_rate, unit: "£") %></p>
            </div>
          <div class="d-flex justify-content-between">
            <p class="product-location"><%= hat.location%></p>
            <p class="product-rating"><%= average_rating %><i class="fa-solid fa-star"></i></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/profile.html.erb
<% @hats.each do |hat| %>
  <p><%= hat.location %></p>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => 1..5 %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Review your booking</h1>
        <div class="mt-3">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    OnlyHats - headgear for all occasions
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-lg-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_hats.png", alt: "Only Hats"%>
    <% end %>
    </a>


    <div id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
           <li class="nav-item">
            <%= link_to "Explore hats", hats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Vintage", hats_path(type: "vintage"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Party", hats_path(type: "party"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Formal", hats_path(type: "formal"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to users_show_path do %>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar", id: "navbarDropdown" %>
              <% else %>
                <%= link_to "Profile", users_show_path, class: "nav-link" %>
              <% end %>
            <% end %>
          </li>


          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8">
      <h1>Hi, I am <%= @user.first_name %></h1>
      <p><strong>Bio:</strong> <%= @user.bio %></p>
    </div>
    <div class="col-md-4">
      <div class="avatar-wrapper">
        <%= cl_image_tag current_user.photo.key, width: 550, height: 550, crop: :thumb, gravity: :face, class: "avatar-square" %>
      </div>
    </div>
  </div>

<div class="bookings-list">
  <h2>My bookings</h2>
  <% if @user.bookings.any? %>
    <div class="row">
      <% @user.bookings.each do |booking| %>
        <div class="col-md-4">
          <div class="hat-card">
            <div class="hat-card-image rounded-4" style="background-image: url('<%= cl_image_path booking.hat.photo.key, crop: :fill %>')"></div>
            <div class="hat-card-content">
              <h5 class="hat-card-title"><%= booking.hat.name %></h5>
              <div class="mb-3">
                <% if booking.hat.day_rate %>
                  <%= booking.start_date.strftime("%d %B %Y") %> - <%= booking.end_date.strftime("%d %B %Y") %> ·
                  <% num_days = (booking.end_date.to_date - booking.start_date.to_date).to_i %>
                  <%= number_to_currency(booking.hat.day_rate * num_days, unit: "£") %>
                <% end %>
              </div>
              <% if booking.end_date < Time.now && booking.review.nil? && booking.status == true %>
                <%= link_to "Review hat", new_booking_review_path(booking_id: booking.id), class: "btn btn-primary" %>
              <% elsif booking.end_date < Time.now && booking.review %>
                <%= link_to "Review submitted", hat_path(booking.hat), class: "btn btn-primary" %>
              <% elsif booking.status == false %>
                <%= "Booking declined" %>
              <% elsif booking.status == true %>
                <%= "Booking accepted" %>
              <% else %>
                <%= "Booking pending" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No bookings found.</p>
  <% end %>
</div>